server:
  port: 8084

spring:
  application:
    name: Notification Service

  datasource:
    url: jdbc:mysql://localhost:3306/notification_db
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect