server:
  port: 8080

# using this we can show one service at a time on swagger
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    urls:
#      - name: user-service
#        url: http://localhost:8086/v3/api-docs
#      - name: vendor-service
#        url: http://localhost:8087/v3/api-docs

# this is used to show multiple services at same time on swagger
springdoc:
  swagger-ui:
    path: /swagger-ui
    url: /merged-api-docs

spring:
  webflux:
    static-path-pattern: /swagger-ui/**

  security:
    user:
      name: admin
      password: admin
  application:
    name: api-gateway

  cloud:
    discovery:
      enabled: false
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/v1/users/**
            - id: vendor-service
              uri: http://localhost:8087
              predicates:
                - Path=/api/v1/vendor/**
            - id: inventory-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/categories/**
                - Path=/api/v1/item-availability/**
                - Path=/api/v1/item/**
