server:
  port: 8082

spring:
  application:
    name: Booking Service

  datasource:
    url: jdbc:mysql://localhost:3306/booking_db
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect