server:
  port: 8085

spring:
  application:
    name: Payment Service

  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
