server:
  port: 8081

spring:
  application:
    name: Admin Service

  datasource:
    url: jdbc:mysql://localhost:3306/admin_db
    username: root
    password: admin

services:
  user-service:
    url: http://localhost:8086/
  vendor-service:
    url: http://localhost:8087/