version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql_db_user_service
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DB_PASSWORD
      MYSQL_DATABASE: DB_NAME
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  user-service:
    image: user-service:1.0
    container_name: user_service_container
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: DB_URL
      SPRING_DATASOURCE_USERNAME: DB_USERNAME
      SPRING_DATASOURCE_PASSWORD: DB_PASSWORD
      SERVER_PORT: 8086
    ports:
      - "8086:8086"

volumes:
  mysql_data: